package org.lamisplus.modules.hts.domain.entity;

import com.fasterxml.jackson.databind.JsonNode;
import com.vladmihalcea.hibernate.type.json.JsonBinaryType;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "hts_ict_contact")
@Data
@EqualsAndHashCode(callSuper = false)
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
@EntityListeners(AuditingEntityListener.class)
public class IctContact {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Generated by the database via gen_random_uuid().
     * insertable=false, updatable=false — Hibernate never touches this column.
     */
    @Column(columnDefinition = "uuid", insertable = false, updatable = false, unique = true, nullable = false)
    private UUID uuid;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ict_encounter_id", nullable = false)
    private IctEncounter ictEncounter;

    /**
     * Renamed from contact_id → contact_code (item 7).
     * Frontend-generated human-readable code, e.g. ICT-CLIENT001-1-abc123.
     */
    @Column(name = "contact_code", length = 100)
    private String contactCode;

    /** Renamed: firstname_of_contact → first_name (item 6) */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /** Renamed: middlename_of_contact → middle_name (item 6) */
    @Column(name = "middle_name")
    private String middleName;

    /** Renamed: surname_of_contact → surname (item 6) */
    @Column(name = "surname", nullable = false)
    private String surname;

    @Column(name = "relationship_to_index", length = 100)
    private String relationshipToIndex;

    /** Renamed: contact_sex → sex (item 6) */
    @Column(name = "sex", length = 20)
    private String sex;

    // contact_age_group REMOVED (item 5)
    // contact_age       REMOVED (item 5)

    /** Renamed: contact_phone → phone (item 6) */
    @Column(name = "phone", length = 20)
    private String phone;

    /** Renamed: contact_address → address (item 6) */
    @Column(name = "address", columnDefinition = "TEXT")
    private String address;

    @Column(name = "same_address_as_index")
    private Boolean sameAddressAsIndex = false;

    @Column(name = "notification_method", length = 100)
    private String notificationMethod;

    @Column(name = "follow_up_location", length = 100)
    private String followUpLocation;

    @Column(name = "attempts")
    private Integer attempts = 0;

    @Column(name = "known_hiv_positive", length = 10)
    private String knownHivPositive;

    @Column(name = "hiv_test_result", length = 20)
    private String hivTestResult;

    @Column(name = "date_tested_hiv")
    private LocalDate dateTestedHiv;

    @Column(name = "date_enrolled_art")
    private LocalDate dateEnrolledArt;

    /** Renamed: contact_art_clinic → art_clinic (item 6) */
    @Column(name = "art_clinic")
    private String artClinic;

    /** Renamed: contact_on_art → on_art (item 6) */
    @Column(name = "on_art")
    private String onArt;

    @Column(name = "enrolled_in_ovc")
    private Boolean enrolledInOvc = false;

    @Column(name = "date_enrolled_ovc")
    private LocalDate dateEnrolledOvc;

    @Column(name = "ovc_id", length = 100)
    private String ovcId;

    /** JSONB overflow for future/optional contact fields */
    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private JsonNode data;

    /** BOOLEAN — false = active, true = soft-deleted. */
    @Column(nullable = false)
    private Boolean archived = false;

    @CreatedBy
    @Column(name = "created_by")
    private String createdBy;

    @CreatedDate
    @Column(name = "date_created")
    private LocalDateTime dateCreated;

    @LastModifiedBy
    @Column(name = "modified_by")
    private String modifiedBy;

    @LastModifiedDate
    @Column(name = "last_modified_date")
    private LocalDateTime lastModifiedDate;
}