import { useFormik } from "formik";
import { buildValidationSchema } from "./validationSchema";

const initialValues = {
  dateOfVisit: "",
  clientCode: "",
  setting: "",
  facilitySetting: "",
  facilityName: "",
  communityEntryPoint: "",
  modality: "",
  typeOfSession: "",
  indexTesting: "",
  indexRelationship: "",
  indexClientCode: "",
  surname: "",
  firstName: "",
  middleName: "",
  dobType: "Actual",
  dateOfBirth: "",
  age: "",
  sex: "",
  phoneNumber: "",
  maritalStatus: "",
  numberOfWives: "",
  numberOfCoWives: "",
  numberOfBiologicalChildren: "",
  pregnancyStatus: "",
  breastfeedingDuration: "",
  clientState: "",
  clientLga: "",
  address: "",
  landmark:"",
  previouslyTestedNegative: "",
  timeOfLastNegativeTest: "",
  clientInformedTransmissionRoutes: "",
  clientInformedRiskFactors: "",
  clientInformedPreventionMethods: "",
  clientInformedPossibleResults: "",
  informedConsentGiven: "",
  everHadSexualIntercourse: "",
  moreThanOneSexPartner: "",
  unprotectedVaginalSex: "",
  unprotectedAnalSex: "",
  bloodTransfusionLast3Months: "",
  sexUnderInfluence: "",
  historyOfSTI: "",
  currentCough: "",
  weightLoss: "",
  fever: "",
  nightSweats: "",
  complaintsVaginalDischarge: "",
  complaintsLowerAbdominalPain: "",
  complaintsUrethralDischarge: "",
  complaintsScroralSwelling: "",
  complaintsGenitalSores: "",
  complaintsSwollenLymphNodes: "",
  partnerNewlyDiagnosed: "",
  partnerPregnantOnArv: "",
  adolescentHivPositive: "",
  partnerNotRegularlyOnDrugs: "",
  partnerRecentlyReturnedToTreatment: "",
  hivEarlyDetectTestDone: "",
  initialHivTest: "",
  suspectedAcuteInfection: "",
  confirmatoryHivTest: "",
  syphilisTestResult: "",
  recencyTest: "",
  previouslyTestedThisYear: "",
  clientReceivedTestResult: "",
  hivTestKitsProvided: "",
  categoryOfClients: "",
  acceptedIndexTesting: "",
  providedFpInfo: "",
  clientPartnerUseFpMethods: "",
  clientPartnerUseCondoms: "",
  correctCondomUseDemonstrated: "",
  condomsProvided: "",
  clientReferredToOtherServices: "",
  completedBy: "",
  designation: "",
  sexCode: "",
  maritalStatusCode:"",
  currentOrganisationUnitId: ""
};

export const useNewPatientFormik = (onSubmit) => {
  const formik = useFormik({
    initialValues,
    validationSchema: buildValidationSchema(true),
    onSubmit,
  });
  return { formik };
};